apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-runner
  labels:
    app: github-actions-runner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-actions-runner
  template:
    metadata:
      labels:
        app: github-actions-runner
    spec:
      containers:
      - name: runner
        image: anirudh077/gh-action-runner:python3
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
        resources:
          limits:
            cpu: 500m
            memory: 4Gi
        imagePullPolicy: Always
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock