name:  gh-runner-image-push

on:
  push:
    branches:
      - 'main'
    paths:
      - 'github-runner/**'    
  
env:
  CI: false

jobs:
  build_deploy:
    runs-on: self-hosted
  
    steps:
      - uses: actions/checkout@v3
        name: checkout repo
      
      - name: Build and push Image
        shell: bash
        env:
          REGISTRY: anirudh077
          IMAGENAME: gh-action-runner
          TAGNAME: python3
        run: |
          #!/bin/bash/
          cd github-runner
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t ${REGISTRY}/${IMAGENAME}:${TAGNAME} --build-arg GITHUB_TOKEN=${{ secrets.DOCKER_USERNAME }} --build-arg GITHUB_REPOSITORY={{ env.GITHUB_REPOSITORY }} .
          docker push ${REGISTRY}/${IMAGENAME}:${TAGNAME}