name:  gh-runner-image-push

on:
  push:
    branches:
      - 'main'
    paths:
      - 'python-app/**'    
  
env:
  CI: false

jobs:
  build_deploy:
    runs-on: ubuntu-20.04
  
    steps:
      - uses: actions/checkout@v3
        name: checkout repo
      
      - name: Build and push Image
        shell: bash
        env:
          REGISTRY: anirudh077
          IMAGENAME: python-app
          TAGNAME: latest
        run: |
          #!/bin/bash/
          cd python-app
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t ${REGISTRY}/${IMAGENAME}:${TAGNAME} .
          docker push ${REGISTRY}/${IMAGENAME}:${TAGNAME}